services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_USER: ml_user
      MONGO_PASSWORD: ml_password
      MONGO_DB: ml_data
    networks:
      - app_network

  web_app:
    build: ./web-app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://movie_user:movie_password_321@mongodb:27017/ml_data
    networks:
      - app_network

  ml_client:
    build: ./machine-learning-client
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://movie_user:movie_password_321@mongodb:27017/ml_data
    networks:
      - app_network

  movie_seeder:
    build: ./mongo-init
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge