name: Build and run application (MongoDB, ML Client, Web App, and entire application)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Build and run the full system
      - name: Build and run full system with Docker Compose
        run: docker compose up --build -d
